#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define About_box                               40000
#define Dummy_check_box_2                       40000
#define Archive_Progress                        40001
#define Dummy_check_box_1                       40001
#define AZip_Doc_Icon                           40002
#define AZip_Icon                               40003
#define AZip_URL                                40004
#define Binoculars_Icon                         40005
#define Cancel_button                           40006
#define Comment_1                               40007
#define Comment_2                               40008
#define Comp_ratio                              40009
#define Comp_size                               40010
#define Confirm_Icon                            40011
#define Confirm_Password_Label                  40012
#define Conflict_location                       40013
#define Conflict_simple_name                    40014
#define Content_to_be_searched                  40015
#define Copyright_label                         40016
#define Credits_box                             40017
#define Credits_button                          40018
#define Drag_Unpack_Icon                        40019
#define Drop_archive_name                       40020
#define Drop_files_box                          40021
#define Encrypt_check_box                       40022
#define Encrypted_entry                         40023
#define Entry_name                              40024
#define Entry_operation_name                    40025
#define File_exists_box                         40026
#define File_Progress                           40027
#define Find_box                                40028
#define Folders_BMP                             40029
#define GNAT_URL                                40030
#define GNAT_Version                            40031
#define GNAVI_URL                               40032
#define ID_Button_About_Azip                    40033
#define IDM__ABOUT                              40034
#define IDM__CLOSE_ARCHIVE                      40035
#define IDM__FLAT_VIEW                          40036
#define IDM__NEW_ARCHIVE                        40037
#define IDM__OPEN_ARCHIVE                       40038
#define IDM__QUIT                               40039
#define IDM__RECOMPRESS_ARCHIVE                 40040
#define IDM__TREE_VIEW                          40041
#define IDM_ADD_FILES                           40042
#define IDM_Add_Files_Encryption                40043
#define IDM_Add_Folder                          40044
#define IDM_Add_Folder_Encryption               40045
#define IDM_AZip_Web_news                       40046
#define IDM_COMPARE_ARCHIVES                    40047
#define IDM_Delete_selected                     40048
#define IDM_Encrypt_Archive                     40049
#define IDM_EXTRACT                             40050
#define IDM_FIND_IN_ARCHIVE                     40051
#define IDM_MERGE_ARCHIVES                      40052
#define IDM_MRU_1                               40053
#define IDM_MRU_2                               40054
#define IDM_MRU_3                               40055
#define IDM_MRU_4                               40056
#define IDM_MRU_5                               40057
#define IDM_MRU_6                               40058
#define IDM_MRU_7                               40059
#define IDM_MRU_8                               40060
#define IDM_MRU_9                               40061
#define IDM_Properties                          40062
#define IDM_Quick_Help                          40063
#define IDM_SAVE_ARCHIVE_AS                     40064
#define IDM_Select_all                          40065
#define IDM_TEST_ARCHIVE                        40066
#define IDM_Touch_Time_Stamps                   40067
#define IDM_Unselect_all                        40068
#define IDM_UPDATE_ARCHIVE                      40069
#define IDM_Web                                 40070
#define IDM_WINDOW_CASCADE                      40071
#define IDM_WINDOW_CLOSE_ALL                    40072
#define IDM_WINDOW_TILE_HORIZONTAL              40073
#define IDM_WINDOW_TILE_VERTICAL                40074
#define Ini_files_URL                           40075
#define Key_Icon                                40076
#define Menu_MDI_Child                          40077
#define Menu_MDI_Main                           40078
#define Name_to_be_searched                     40079
#define New_archive_msg                         40080
#define Numb_entries                            40081
#define Overwrite_All                           40082
#define Overwrite_No                            40083
#define Overwrite_None                          40084
#define Overwrite_Rename                        40085
#define Overwrite_Yes                           40086
#define Password_confirm_edit                   40087
#define Password_decryption_box                 40088
#define Password_edit                           40089
#define Password_encryption_box                 40090
#define Plus_icon                               40091
#define Progress_box                            40092
#define Properties_box                          40093
#define Quick_help_box                          40094
#define ResEdit_URL                             40095
#define Show_password_box                       40096
#define Stats_list                              40097
#define Toolbar_BMP                             40098
#define Uncomp_size                             40099
#define Version_label                           40100
#define Wait_refresh_box                        40101
#define ZipAda_URL                              40102
#define ZipAda_Version                          40103
#define IDM_Toggle_Flat_Tree_View               40104
#define Fake_menu_for_commands_in_no_real_menu  40105
#define IDM_No_sorting                          40106
#define Select_column_box                       40107
#define IDM_Select_columns                      40108
