#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define Menu_MDI_Main                           102
#define Menu_MDI_Child                          104
#define About_box                               107
#define Progress_box                            109
#define Find_box                                111
#define AZip_Doc_Icon                           112
#define AZip_Icon                               114
#define File_exists_box                         118
#define Password_input_box                      119
#define Archive_Progress                        1000
#define Conflict_simple_name                    1000
#define Encrypted_entry                         1000
#define GNAT_URL                                1000
#define Entry_operation_name                    1001
#define GNAT_Version                            1001
#define Conflict_location                       1002
#define File_Progress                           1002
#define GNAVI_URL                               1002
#define Name_to_be_searched                     1002
#define Show_password_box                       1002
#define Cancel_button                           1003
#define Version_label                           1003
#define Content_to_be_searched                  1004
#define ResEdit_URL                             1004
#define Credits_button                          1005
#define Entry_name                              1005
#define Password_edit                           1005
#define Overwrite_Yes                           1006
#define Overwrite_No                            1008
#define IDM__NEW_ARCHIVE                        40000
#define IDM__OPEN_ARCHIVE                       40001
#define IDM_MRU_1                               40002
#define IDM_Unselect_all                        40002
#define IDM__ABOUT                              40003
#define IDM__TEST_ARCHIVE                       40004
#define IDM__QUIT                               40005
#define IDM__RECOMPRESS_ARCHIVE                 40006
#define IDM_EXTRACT                             40007
#define IDM_FIND_IN_ARCHIVE                     40008
#define IDM_COMPARE_ARCHIVES                    40009
#define IDM__FLAT_VIEW                          40010
#define IDM__TREE_VIEW                          40011
#define IDM_MRU_2                               40012
#define IDM_MRU_3                               40013
#define IDM_MRU_4                               40014
#define IDM_MRU_5                               40015
#define IDM_MRU_6                               40016
#define IDM_MRU_7                               40017
#define IDM_MRU_8                               40018
#define IDM_MRU_9                               40019
#define IDM_WINDOW_CASCADE                      40020
#define IDM_WINDOW_TILE_HORIZONTAL              40021
#define IDM_WINDOW_TILE_VERTICAL                40022
#define IDM_WINDOW_CLOSE_ALL                    40023
#define IDM_MERGE_ARCHIVES                      40024
#define AZip_URL                                40025
#define IDM_Select_all                          40025
#define IDM_Delete_selected                     40026
#define IDM_ADD_FILES                           40027
#define IDM_FRESHEN_ARCHIVE                     40028
#define ZipAda_Version                          40028
#define IDM__CLOSE_ARCHIVE                      40029
#define ZipAda_URL                              40029
#define IDM__SAVE_ARCHIVE_AS                    40031
#define Overwrite_All                           40032
#define Overwrite_None                          40034
#define Overwrite_Rename                        40036
