-- GWindows test application, generated by GWenerator

with GWindows.Application;        use GWindows.Application;
with GWindows.Base;               use GWindows.Base;
with GWindows.GStrings;           use GWindows.GStrings;
with GWindows.Message_Boxes;      use GWindows.Message_Boxes;

with AZip_GWin.MDI_Main; use AZip_GWin.MDI_Main;

with Ada.Exceptions;
with GNAT.Traceback.Symbolic;

procedure AZip is

  Top: AZip_GWin.MDI_Main.MDI_Main_Type;

  procedure Interactive_crash(
    Window : in out GWindows.Base.Base_Window_Type'Class;
    E: Ada.Exceptions.Exception_Occurrence)
  is
    pragma Unreferenced (Window);
    small_insult: constant String:=
        Ada.Exceptions.Exception_Name (E) & ASCII.LF &
        Ada.Exceptions.Exception_Message (E);
    insult: constant String:=
        small_insult & ASCII.LF &
        GNAT.Traceback.Symbolic.Symbolic_Traceback(E);
  begin
    GWindows.Base.On_Exception_Handler (Handler => null); -- Avoid infinite recursion!
    Message_Box
      ("Crash in AZip (GWindows)",
        To_GString_from_String(insult),
        OK_Box
      );
  end Interactive_crash;

begin
    GWindows.Base.On_Exception_Handler (Handler => Interactive_crash'Unrestricted_Access);
    Create_MDI_Top (Top, "AZip");
    Message_Loop;
end AZip;
